### ISSUE TITLE
Startup Error: Unable to detect graphics environment

### ISSUE THREAD

**Issue by HenryGuillen17** [rycus86/docker-intellij-idea#7]
Hi.
I tried to run:

`docker run --rm \
  -e DISPLAY=${DISPLAY} \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v ~/.Idea:/home/developer/.Idea \
  -v ~/.Idea.java:/home/developer/.java \
  -v ~/.Idea.maven:/home/developer/.m2 \
  -v ~/.Idea.gradle:/home/developer/.gradle \
  -v ~/.Idea.share:/home/developer/.local/share/JetBrains \
  -v ~/Project:/home/developer/Project \
  --name idea-$(head -c 4 /dev/urandom | xxd -p)-$(date +'%Y%m%d-%H%M%S') \
rycus86/intellij-idea:latest`

it results in:

`Startup Error: Unable to detect graphics environment`

What can I do?

My OS is OSX 10.13.6 High Sierra and Docker version 19.03.4, build 9013bf5

Thanks.

**Comment by rycus86** [comment]
Hi @HenryGuillen17 

On OS X, you'll need XQuartz to provide a Linux-like X environment, then that will give you the display number.

**Comment by HenryGuillen17** [comment]
Ok, thanks for help me
I installed [XQuartz](https://www.xquartz.org/) and now i got this:
`OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.

Start Failed: Failed to initialize graphics environment

java.awt.AWTError: Can't connect to X11 window server using '/private/tmp/com.apple.launchd.UrdE2Nfjts/org.macosforge.xquartz:0' as the value of t
	at java.desktop/sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:102)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:61)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.createGE(GraphicsEnvironment.java:101)
	at java.desktop/java.awt.GraphicsEnvironment$LocalGE.<clinit>(GraphicsEnvironment.java:83)
	at java.desktop/java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:129)
	at java.desktop/sun.awt.X11.XToolkit.<clinit>(XToolkit.java:232)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:588)
	at java.desktop/java.awt.Toolkit$2.run(Toolkit.java:583)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.Toolkit.getDefaultToolkit(Toolkit.java:582)
	at java.desktop/java.awt.Toolkit.getEventQueue(Toolkit.java:1499)
	at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1318)
	at com.intellij.idea.StartupUtil.lambda$prepareAndStart$2(StartupUtil.java:171)
	at java.base/java.util.concurrent.CompletableFuture.asyncRunStage(CompletableFuture.java:1750)
	at java.base/java.util.concurrent.CompletableFuture.runAsync(CompletableFuture.java:1959)
	at com.intellij.idea.StartupUtil.prepareAndStart(StartupUtil.java:150)
	at com.intellij.idea.MainImpl.start(MainImpl.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.ide.plugins.MainRunner.lambda$start$0(MainRunner.java:58)
	at java.base/java.lang.Thread.run(Thread.java:834)

-----
JRE 11.0.4+10-b304.77 amd64 by JetBrains s.r.o
/opt/idea/jbr`

I have researched on the internet, I have tried to execute several commands but I have not been able to resolve this issue either.

Thank you for your help.

**Comment by rycus86** [comment]
Try running `xhost +`
If I remember correctly, you need this on OS X to disable X security :(
You'll also have to do this every time you log in to the Mac.

**Comment by rycus86** [comment]
Did this help you resolve this issue?

**Comment by HenryGuillen17** [comment]
No, I could never solve that, I gave up, and on the internet you don't get much information about it. Same thanks for your help.

**Comment by rycus86** [comment]
Sorry about that! I have managed to run these on OS X a while back but admittedly haven't tried it for some time.

**Comment by hitesh-sm** [comment]
I installed Xquartz, would it fill up ${DISPLAY}
Because when i do echo ${DISPLAY} i get nothing

**Comment by rycus86** [comment]
> I installed Xquartz, would it fill up ${DISPLAY}
> Because when i do echo ${DISPLAY} i get nothing

Yes, I believe it should set the `$DISPLAY` variable, see https://discussions.apple.com/thread/4157422 for example. Have you restarted your terminal after installing & enabling XQuartz?

**Comment by hitesh-sm** [comment]
Yes i did restart and I checked "launchctl list | grep xquartz" to see if the XQuartz User Launch Agent, it is running.
But when I do echo ${DISPLAY}, i get a blank line
